name: BlockBreakDamage
version: ${project.version}
main: me.endergamingfilms.blockbreakdamage.BlockBreakDamage
api-version: 1.16
authors: [ EnderGamingYT ]
commands:
  bbd:
    permission: BlockBreakDamage.admin
    default: op
